/*  CREATE DATABASE  */
DROP DATABASE IF EXISTS employeeDB;
CREATE DATABASE employeeDB;
USE employeeDB;

/*  CREATE TABLE FOR DEPARTMENT  */
CREATE TABLE department (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NULL,
    PRIMARY KEY (id),
);

/*  CREATE TABLE FOR ROLE  */
CREATE TABLE role (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(30) NULL,
salary DECIMAL(10.3) NULL,
department_id INT NULL,
PRIMARY KEY (id),
);

/*  CREATE TABLE FOR EMPLOYEE  */
CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(45) NULL,
last_name VARCHAR(45) NULL,
role_id INT NULL,
manager_id INT NULL,
PRIMARY KEY (id),
);